# Generated by Django 6.1.1 on 2026-10-05 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
        ("runs", "0002_auditfinding"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewdecision",
            name="finding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="decisions",
                to="runs.auditfinding",
            ),
        ),
    ]
