# Generated by Django 6.1.1 on 2026-10-05 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("notes", "0001_initial"),
        ("reference", "0002_trigram_search"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("coding", "Coding"), ("audit", "Audit")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("ready_for_review", "Ready For Review"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("submitted_codes", models.JSONField(blank=True, default=list)),
                ("pipeline_version", models.CharField(default="1", max_length=20)),
                ("prompt_versions", models.JSONField(blank=True, default=dict)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("dropped_quotes", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=30)),
                ("error_message", models.CharField(blank=True, max_length=300)),
                (
                    "code_set",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reference.codesetversion",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "hcc_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reference.hccmodel",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="notes.note",
                    ),
                ),
                (
                    "retry_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retries",
                        to="runs.run",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("historical", "Historical"),
                            ("resolved", "Resolved"),
                            ("uncertain", "Uncertain"),
                            ("negated", "Negated"),
                            ("family_history", "Family History"),
                        ],
                        max_length=15,
                    ),
                ),
                ("specificity_details", models.JSONField(blank=True, default=list)),
                ("quotes", models.JSONField(blank=True, default=list)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="runs.run",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("display_code", models.CharField(max_length=8)),
                ("description", models.TextField()),
                ("hcc_number", models.PositiveIntegerField(blank=True, null=True)),
                ("hcc_label", models.CharField(blank=True, max_length=200)),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("meat", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        max_length=6,
                    ),
                ),
                ("confidence_reasons", models.JSONField(blank=True, default=list)),
                ("rationale", models.TextField(blank=True)),
                ("flags", models.JSONField(blank=True, default=list)),
                ("candidate_rank", models.PositiveIntegerField()),
                (
                    "condition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestions",
                        to="runs.condition",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="runs.run",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["status", "created_at"], name="runs_run_status_2908ff_idx"),
        ),
    ]
