# Generated by Django 6.1.1 on 2026-10-05 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("submitted_code", models.CharField(blank=True, max_length=8)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("SUPPORTED", "Supported"),
                            ("WEAK_SUPPORT", "Weak Support"),
                            ("SPECIFICITY_MISMATCH", "Specificity Mismatch"),
                            ("NOT_SUPPORTED", "Not Supported"),
                            ("INVALID_CODE", "Invalid Code"),
                            ("MISSED_HCC", "Missed Hcc"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason_code", models.CharField(max_length=30)),
                ("reason", models.TextField()),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("suggested_code", models.CharField(blank=True, max_length=8)),
                (
                    "related_condition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="runs.condition",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="runs.run",
                    ),
                ),
            ],
        ),
    ]
