# Generated by Django 6.1.1 on 2026-10-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LlmCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_hash", models.CharField(max_length=64, unique=True)),
                ("response_json", models.JSONField()),
                ("model_name", models.CharField(max_length=100)),
                ("prompt_version", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "LLM cache entries",
            },
        ),
        migrations.CreateModel(
            name="LlmCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("run_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "step",
                    models.CharField(
                        choices=[("extract", "Extract"), ("select", "Select")], max_length=10
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("prompt_version", models.CharField(max_length=10)),
                ("request_hash", models.CharField(max_length=64)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("cache_hit", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(choices=[("ok", "Ok"), ("error", "Error")], max_length=10),
                ),
                ("error_type", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
