# Generated by Django 6.1.1 on 2026-10-05 06:09

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodeSetVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("system", models.CharField(default="ICD10CM", max_length=20)),
                ("fiscal_year", models.PositiveIntegerField()),
                ("effective_from", models.DateField()),
                ("source_url", models.URLField()),
                ("sha256", models.CharField(max_length=64)),
                ("loaded_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("system", "fiscal_year"), name="uniq_system_fy")
                ],
            },
        ),
        migrations.CreateModel(
            name="HccModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(default="CMS-HCC", max_length=20)),
                ("version", models.CharField(max_length=10)),
                ("payment_year", models.PositiveIntegerField()),
                ("source_url", models.URLField()),
                ("sha256", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "version", "payment_year"), name="uniq_hcc_model"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HccCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("label", models.CharField(max_length=200)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="reference.hccmodel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "HCC categories",
            },
        ),
        migrations.CreateModel(
            name="Icd10Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=7)),
                ("display_code", models.CharField(max_length=8)),
                ("short_desc", models.CharField(max_length=60)),
                ("long_desc", models.TextField()),
                ("is_billable", models.BooleanField()),
                ("category", models.CharField(max_length=3)),
                ("parent_code", models.CharField(blank=True, max_length=7)),
                ("notes", models.JSONField(blank=True, default=dict)),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(null=True)),
                (
                    "code_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="reference.codesetversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Icd10HccMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=7)),
                (
                    "code_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reference.codesetversion"
                    ),
                ),
                (
                    "hcc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reference.hcccategory"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="reference.hccmodel",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="hcccategory",
            constraint=models.UniqueConstraint(fields=("model", "number"), name="uniq_hcc_number"),
        ),
        migrations.AddIndex(
            model_name="icd10code",
            index=models.Index(
                fields=["code_set", "category"], name="reference_i_code_se_f92154_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="icd10code",
            index=models.Index(
                fields=["code_set", "is_billable"], name="reference_i_code_se_e44015_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="icd10code",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="icd10_search_vector_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="icd10code",
            constraint=models.UniqueConstraint(
                fields=("code_set", "code"), name="uniq_codeset_code"
            ),
        ),
        migrations.AddIndex(
            model_name="icd10hccmap",
            index=models.Index(fields=["code_set", "code"], name="reference_i_code_se_16a6bd_idx"),
        ),
        migrations.AddConstraint(
            model_name="icd10hccmap",
            constraint=models.UniqueConstraint(
                fields=("model", "code", "hcc"), name="uniq_code_hcc"
            ),
        ),
    ]
